// Automatically generated by forge bind-json.

pragma solidity >=0.6.2 <0.9.0;
pragma experimental ABIEncoderV2;

import {BettingPool} from "src/BettingPool.sol";
import {GameEngine} from "src/GameEngine.sol";
import {SeasonPredictor} from "src/SeasonPredictor.sol";
import {IGameEngine} from "src/interfaces/IGameEngine.sol";

interface Vm {
    function parseJsonTypeArray(string calldata json, string calldata key, string calldata typeDescription) external pure returns (bytes memory);
    function parseJsonType(string calldata json, string calldata typeDescription) external pure returns (bytes memory);
    function parseJsonType(string calldata json, string calldata key, string calldata typeDescription) external pure returns (bytes memory);
    function serializeJsonType(string calldata typeDescription, bytes memory value) external pure returns (string memory json);
    function serializeJsonType(string calldata objectKey, string calldata valueKey, string calldata typeDescription, bytes memory value) external returns (string memory json);
}
        
library JsonBindings {
    Vm constant vm = Vm(address(uint160(uint256(keccak256("hevm cheat code")))));

    string constant schema_Match_0 = "Match(uint256 homeTeamId,uint256 awayTeamId,uint8 homeScore,uint8 awayScore,uint8 outcome,bool settled,uint256 homeOdds,uint256 awayOdds,uint256 drawOdds)";
    string constant schema_Team_0 = "Team(string name,uint256 wins,uint256 draws,uint256 losses,uint256 points,uint256 goalsFor,uint256 goalsAgainst)";
    string constant schema_Season_0 = "Season(uint256 seasonId,uint256 startTime,uint256 currentRound,bool active,bool completed,uint256 winningTeamId)";
    string constant schema_Prediction_0 = "Prediction(uint256 matchIndex,uint8 predictedOutcome)";
    string constant schema_Bet = "Bet(address bettor,uint256 roundId,uint256 amount,Prediction[] predictions,uint256 potentialPayout,uint256 basePayout,uint256 poolBonus,uint256 lockedLPLiquidity,uint256 timestamp,bool settled,bool won)Prediction(uint256 matchIndex,uint8 predictedOutcome)";
    string constant schema_MatchBettingData = "MatchBettingData(uint256 totalHomeAmount,uint256 totalAwayAmount,uint256 totalDrawAmount,uint256 totalBets)";
    string constant schema_Match_1 = "Match(uint256 homeTeamId,uint256 awayTeamId,uint8 homeScore,uint8 awayScore,uint8 outcome,bool settled,uint256 homeOdds,uint256 awayOdds,uint256 drawOdds)";
    string constant schema_Team_1 = "Team(string name,uint256 wins,uint256 draws,uint256 losses,uint256 points,uint256 goalsFor,uint256 goalsAgainst)";
    string constant schema_Season_1 = "Season(uint256 seasonId,uint256 startTime,uint256 currentRound,bool active,bool completed,uint256 winningTeamId)";
    string constant schema_Round = "Round(uint256 roundId,uint256 seasonId,uint256 startTime,uint256 vrfRequestId,bool settled,Match[10] matches)Match(uint256 homeTeamId,uint256 awayTeamId,uint8 homeScore,uint8 awayScore,uint8 outcome,bool settled,uint256 homeOdds,uint256 awayOdds,uint256 drawOdds)";
    string constant schema_Prediction_1 = "Prediction(address predictor,uint256 seasonId,uint256 predictedTeamId,uint256 timestamp,bool claimed)";

    function serialize(IGameEngine.Match memory value) internal pure returns (string memory) {
        return vm.serializeJsonType(schema_Match_0, abi.encode(value));
    }

    function serialize(IGameEngine.Match memory value, string memory objectKey, string memory valueKey) internal returns (string memory) {
        return vm.serializeJsonType(objectKey, valueKey, schema_Match_0, abi.encode(value));
    }

    function deserializeMatch_0(string memory json) public pure returns (IGameEngine.Match memory) {
        return abi.decode(vm.parseJsonType(json, schema_Match_0), (IGameEngine.Match));
    }

    function deserializeMatch_0(string memory json, string memory path) public pure returns (IGameEngine.Match memory) {
        return abi.decode(vm.parseJsonType(json, path, schema_Match_0), (IGameEngine.Match));
    }

    function deserializeMatch_0Array(string memory json, string memory path) public pure returns (IGameEngine.Match[] memory) {
        return abi.decode(vm.parseJsonTypeArray(json, path, schema_Match_0), (IGameEngine.Match[]));
    }

    function serialize(IGameEngine.Team memory value) internal pure returns (string memory) {
        return vm.serializeJsonType(schema_Team_0, abi.encode(value));
    }

    function serialize(IGameEngine.Team memory value, string memory objectKey, string memory valueKey) internal returns (string memory) {
        return vm.serializeJsonType(objectKey, valueKey, schema_Team_0, abi.encode(value));
    }

    function deserializeTeam_0(string memory json) public pure returns (IGameEngine.Team memory) {
        return abi.decode(vm.parseJsonType(json, schema_Team_0), (IGameEngine.Team));
    }

    function deserializeTeam_0(string memory json, string memory path) public pure returns (IGameEngine.Team memory) {
        return abi.decode(vm.parseJsonType(json, path, schema_Team_0), (IGameEngine.Team));
    }

    function deserializeTeam_0Array(string memory json, string memory path) public pure returns (IGameEngine.Team[] memory) {
        return abi.decode(vm.parseJsonTypeArray(json, path, schema_Team_0), (IGameEngine.Team[]));
    }

    function serialize(IGameEngine.Season memory value) internal pure returns (string memory) {
        return vm.serializeJsonType(schema_Season_0, abi.encode(value));
    }

    function serialize(IGameEngine.Season memory value, string memory objectKey, string memory valueKey) internal returns (string memory) {
        return vm.serializeJsonType(objectKey, valueKey, schema_Season_0, abi.encode(value));
    }

    function deserializeSeason_0(string memory json) public pure returns (IGameEngine.Season memory) {
        return abi.decode(vm.parseJsonType(json, schema_Season_0), (IGameEngine.Season));
    }

    function deserializeSeason_0(string memory json, string memory path) public pure returns (IGameEngine.Season memory) {
        return abi.decode(vm.parseJsonType(json, path, schema_Season_0), (IGameEngine.Season));
    }

    function deserializeSeason_0Array(string memory json, string memory path) public pure returns (IGameEngine.Season[] memory) {
        return abi.decode(vm.parseJsonTypeArray(json, path, schema_Season_0), (IGameEngine.Season[]));
    }

    function serialize(BettingPool.Prediction memory value) internal pure returns (string memory) {
        return vm.serializeJsonType(schema_Prediction_0, abi.encode(value));
    }

    function serialize(BettingPool.Prediction memory value, string memory objectKey, string memory valueKey) internal returns (string memory) {
        return vm.serializeJsonType(objectKey, valueKey, schema_Prediction_0, abi.encode(value));
    }

    function deserializePrediction_0(string memory json) public pure returns (BettingPool.Prediction memory) {
        return abi.decode(vm.parseJsonType(json, schema_Prediction_0), (BettingPool.Prediction));
    }

    function deserializePrediction_0(string memory json, string memory path) public pure returns (BettingPool.Prediction memory) {
        return abi.decode(vm.parseJsonType(json, path, schema_Prediction_0), (BettingPool.Prediction));
    }

    function deserializePrediction_0Array(string memory json, string memory path) public pure returns (BettingPool.Prediction[] memory) {
        return abi.decode(vm.parseJsonTypeArray(json, path, schema_Prediction_0), (BettingPool.Prediction[]));
    }

    function serialize(BettingPool.Bet memory value) internal pure returns (string memory) {
        return vm.serializeJsonType(schema_Bet, abi.encode(value));
    }

    function serialize(BettingPool.Bet memory value, string memory objectKey, string memory valueKey) internal returns (string memory) {
        return vm.serializeJsonType(objectKey, valueKey, schema_Bet, abi.encode(value));
    }

    function deserializeBet(string memory json) public pure returns (BettingPool.Bet memory) {
        return abi.decode(vm.parseJsonType(json, schema_Bet), (BettingPool.Bet));
    }

    function deserializeBet(string memory json, string memory path) public pure returns (BettingPool.Bet memory) {
        return abi.decode(vm.parseJsonType(json, path, schema_Bet), (BettingPool.Bet));
    }

    function deserializeBetArray(string memory json, string memory path) public pure returns (BettingPool.Bet[] memory) {
        return abi.decode(vm.parseJsonTypeArray(json, path, schema_Bet), (BettingPool.Bet[]));
    }

    function serialize(BettingPool.MatchBettingData memory value) internal pure returns (string memory) {
        return vm.serializeJsonType(schema_MatchBettingData, abi.encode(value));
    }

    function serialize(BettingPool.MatchBettingData memory value, string memory objectKey, string memory valueKey) internal returns (string memory) {
        return vm.serializeJsonType(objectKey, valueKey, schema_MatchBettingData, abi.encode(value));
    }

    function deserializeMatchBettingData(string memory json) public pure returns (BettingPool.MatchBettingData memory) {
        return abi.decode(vm.parseJsonType(json, schema_MatchBettingData), (BettingPool.MatchBettingData));
    }

    function deserializeMatchBettingData(string memory json, string memory path) public pure returns (BettingPool.MatchBettingData memory) {
        return abi.decode(vm.parseJsonType(json, path, schema_MatchBettingData), (BettingPool.MatchBettingData));
    }

    function deserializeMatchBettingDataArray(string memory json, string memory path) public pure returns (BettingPool.MatchBettingData[] memory) {
        return abi.decode(vm.parseJsonTypeArray(json, path, schema_MatchBettingData), (BettingPool.MatchBettingData[]));
    }

    function serialize(GameEngine.Match memory value) internal pure returns (string memory) {
        return vm.serializeJsonType(schema_Match_1, abi.encode(value));
    }

    function serialize(GameEngine.Match memory value, string memory objectKey, string memory valueKey) internal returns (string memory) {
        return vm.serializeJsonType(objectKey, valueKey, schema_Match_1, abi.encode(value));
    }

    function deserializeMatch_1(string memory json) public pure returns (GameEngine.Match memory) {
        return abi.decode(vm.parseJsonType(json, schema_Match_1), (GameEngine.Match));
    }

    function deserializeMatch_1(string memory json, string memory path) public pure returns (GameEngine.Match memory) {
        return abi.decode(vm.parseJsonType(json, path, schema_Match_1), (GameEngine.Match));
    }

    function deserializeMatch_1Array(string memory json, string memory path) public pure returns (GameEngine.Match[] memory) {
        return abi.decode(vm.parseJsonTypeArray(json, path, schema_Match_1), (GameEngine.Match[]));
    }

    function serialize(GameEngine.Team memory value) internal pure returns (string memory) {
        return vm.serializeJsonType(schema_Team_1, abi.encode(value));
    }

    function serialize(GameEngine.Team memory value, string memory objectKey, string memory valueKey) internal returns (string memory) {
        return vm.serializeJsonType(objectKey, valueKey, schema_Team_1, abi.encode(value));
    }

    function deserializeTeam_1(string memory json) public pure returns (GameEngine.Team memory) {
        return abi.decode(vm.parseJsonType(json, schema_Team_1), (GameEngine.Team));
    }

    function deserializeTeam_1(string memory json, string memory path) public pure returns (GameEngine.Team memory) {
        return abi.decode(vm.parseJsonType(json, path, schema_Team_1), (GameEngine.Team));
    }

    function deserializeTeam_1Array(string memory json, string memory path) public pure returns (GameEngine.Team[] memory) {
        return abi.decode(vm.parseJsonTypeArray(json, path, schema_Team_1), (GameEngine.Team[]));
    }

    function serialize(GameEngine.Season memory value) internal pure returns (string memory) {
        return vm.serializeJsonType(schema_Season_1, abi.encode(value));
    }

    function serialize(GameEngine.Season memory value, string memory objectKey, string memory valueKey) internal returns (string memory) {
        return vm.serializeJsonType(objectKey, valueKey, schema_Season_1, abi.encode(value));
    }

    function deserializeSeason_1(string memory json) public pure returns (GameEngine.Season memory) {
        return abi.decode(vm.parseJsonType(json, schema_Season_1), (GameEngine.Season));
    }

    function deserializeSeason_1(string memory json, string memory path) public pure returns (GameEngine.Season memory) {
        return abi.decode(vm.parseJsonType(json, path, schema_Season_1), (GameEngine.Season));
    }

    function deserializeSeason_1Array(string memory json, string memory path) public pure returns (GameEngine.Season[] memory) {
        return abi.decode(vm.parseJsonTypeArray(json, path, schema_Season_1), (GameEngine.Season[]));
    }

    function serialize(GameEngine.Round memory value) internal pure returns (string memory) {
        return vm.serializeJsonType(schema_Round, abi.encode(value));
    }

    function serialize(GameEngine.Round memory value, string memory objectKey, string memory valueKey) internal returns (string memory) {
        return vm.serializeJsonType(objectKey, valueKey, schema_Round, abi.encode(value));
    }

    function deserializeRound(string memory json) public pure returns (GameEngine.Round memory) {
        return abi.decode(vm.parseJsonType(json, schema_Round), (GameEngine.Round));
    }

    function deserializeRound(string memory json, string memory path) public pure returns (GameEngine.Round memory) {
        return abi.decode(vm.parseJsonType(json, path, schema_Round), (GameEngine.Round));
    }

    function deserializeRoundArray(string memory json, string memory path) public pure returns (GameEngine.Round[] memory) {
        return abi.decode(vm.parseJsonTypeArray(json, path, schema_Round), (GameEngine.Round[]));
    }

    function serialize(SeasonPredictor.Prediction memory value) internal pure returns (string memory) {
        return vm.serializeJsonType(schema_Prediction_1, abi.encode(value));
    }

    function serialize(SeasonPredictor.Prediction memory value, string memory objectKey, string memory valueKey) internal returns (string memory) {
        return vm.serializeJsonType(objectKey, valueKey, schema_Prediction_1, abi.encode(value));
    }

    function deserializePrediction_1(string memory json) public pure returns (SeasonPredictor.Prediction memory) {
        return abi.decode(vm.parseJsonType(json, schema_Prediction_1), (SeasonPredictor.Prediction));
    }

    function deserializePrediction_1(string memory json, string memory path) public pure returns (SeasonPredictor.Prediction memory) {
        return abi.decode(vm.parseJsonType(json, path, schema_Prediction_1), (SeasonPredictor.Prediction));
    }

    function deserializePrediction_1Array(string memory json, string memory path) public pure returns (SeasonPredictor.Prediction[] memory) {
        return abi.decode(vm.parseJsonTypeArray(json, path, schema_Prediction_1), (SeasonPredictor.Prediction[]));
    }
}
